# Setup
title:               'Octo-Tiger'
tagline:             'an astrophysics program simulating the evolution of star systems'
description:         'Astrophysics program simulating the evolution of star systems based on the fast multipole method on adaptive Octrees'
url:                 https://octotiger.stellar-group.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Octo-Tigers
  url:               https://github.com/STEllAR-GROUP/octotiger
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
github:         https://github.com/STEllAR-GROUP/octotiger
documentation:  https://stellar-group.github.io/octotiger/doc/html/
google_analytics_id: #UA-XXXX-Y
